### PR TITLE
Release 0.1, update to latest revault_tx

### PR DESCRIPTION
**Pull request by darosior**

### CODE REVIEW

**Comment by danielabrozzoni** [comment]
ACK 24d87f4775bc687c64f423846976ec93653a331c - it compiles and tests pass. I'm not sure if something else wanted to be added to the MR

I would like to see this merged as we need it for upgrading revaultd :)

**Comment by darosior** [comment]
I would rather not update to revault_tx's master but rather wait for a 0.3 release there.

**Comment by danielabrozzoni** [comment]
After playing a bit with revaultd I noticed we should update bitcoin to 0.27.0 here as well, I'll open a PR based on this one

**Comment by danielabrozzoni** [comment]
See https://github.com/danielabrozzoni/revault_net/commit/d31bf5b710165e5fdbf9026cc470e9e46139e9d1
Well I thought it would have been more difficult... You can cherry-pick after tagging revault_tx and updating this MR, or change the number yourself 😅

**Comment by darosior** [comment]
Added as 35d2c20

Also added a MSRV and releasing 0.1

**Comment by darosior** [comment]
ACK 517468c

**Pull request merged**
