### PR TITLE
Correct Transaction hex serialization in messages

### PR DESCRIPTION
**Pull request by darosior**
As noted during the review of #46

### CODE REVIEW

**Review by JSwambo — APPROVED** [review]
Ack 06e19ccc209f9eac91da6d9d031a767855c027c2

**Comment by darosior** [comment]
@JSwambo was the ACK for the non-top commit intentional ?

**Comment by darosior** [comment]
I'm in a hurry, going ahead and modifying your comment to ACK the top commit. If this was intentional we can still revert this.

**Comment by darosior** [comment]
ACK fe9ce9b

**Comment by JSwambo** [comment]
> @JSwambo was the ACK for the non-top commit intentional ?

no it wasn't!

**Pull request merged**
